### PR TITLE
feat: add fold, quick fix, gitsigns hls

### PR DESCRIPTION
**Pull request by dmnkgrc**
First of all, thanks for porting this great theme no Neovim 🙏 

I added some missing editor and indent line highlights, as well I added support for Gitsigns

It went from looking like this:

Screenshot 2023-05-20 at 18 27 07

to this:

Screenshot 2023-05-20 at 18 26 32

### CODE REVIEW

**Comment by oxfist** [comment]
@dmnkgrc thank you for your kind words and your changes!! Love to support more plugins. In the upcoming days I'll have time to merge this.

Quick question, do you happen to not have the [gitgutter](https://github.com/airblade/vim-gitgutter) plugin installed? I may have incorrectly linked to their highlight groups, so I just want to confirm.

**Comment by dmnkgrc** [comment]
@oxfist Thanks! No, I don't have it, but I quickly installed it and the colors looked right to me 👍

**Comment by oxfist** [comment]
@dmnkgrc thanks for the confirmation. Now I'm positive the highlight groups for `gitsigns` are currently linked to `gitgutter`'s, hence why you can see them correctly now that you installed it.

The colors were looking right to me too, so I checked and in fact those were linked, so my assumption is that `gitgutter` is probably setting those highlight groups as well. Not everyone will have that plugin installed tho, so we definitely want to support that use case 🙌🏼

**Comment by oxfist** [comment]
@dmnkgrc I reordered some of the highlight definitions and created a new color in the palette for the folded background.

I can't thank you enough for your contribution! I'll try and set up https://allcontributors.org/ in the following days to help recognize contributions properly 🙌🏼  Hopefully we can have this theme support as many plugins and use cases as possible 🚀

**Comment by oxfist** [comment]
@all-contributors please add @dmnkgrc  for bug and code

**Comment by oxfist** [comment]
@all-contributors please add @dmnkgrc for bug, code

**Comment by oxfist** [comment]
@all-contributors please add @dmnkgrc for bug, code

**Comment by oxfist** [comment]
@all-contributors
please add @dmnkgrc for bug
please add @dmnkgrc for code

**Comment by oxfist** [comment]
@all-contributors please add @dmnkgrc for bug and code

**Comment by oxfist** [comment]
@all-contributors please add @dmnkgrc for bug and code

**Pull request merged**
